name: Deploy Demo
run-name: ${{ github.actor }} is testing Package on GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - development
      - deploy
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Verify
      run: mvn -B verify
    
    - name: Package a
      run: chmod +x mvnw

    - name: Package
      run: ./mvnw package
